language : java
jdk :
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wlswlek123@naver.com

before_deploy:
  - zip -r spring-boot *
  - mkdir -p deploy
  - mv spring-boot.zip deploy/spring-boot.zip

deploy:
  - provider : S3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: practice-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir : deploy
    wait-until-deployed : true